import { cfg, defineModule } from "lumi";

export const meta = defineModule({
  name: "economy-games",
  displayName: "Economy Games",
  emoji: "🎰",
  version: "1.0.0",
  description:
    "Blackjack, roulette, crime with jail, work/beg/fish/mine grinds, and a role-granting shop — every payout settled through the addon's own coin ledger.",
  short: "Casino games, crime, grinds, and a shop with its own ledger.",
  endUserDataStatement:
    "Stores per-server wallet balances, jail sentences, shop inventories, cooldown timestamps, and active game tables keyed by user ID. All rows live in this addon's own storage namespace and are removed on GDPR erasure.",
  configSchema: cfg.object({
    currencyName: cfg.string({
      label: "Currency Name",
      description: "Name of the coins games pay out.",
      default: "credits",
      group: "Currency",
    }),
    currencyEmoji: cfg.string({
      label: "Currency Emoji",
      description: "Emoji shown next to amounts.",
      default: "🪙",
      group: "Currency",
    }),
    startingWallet: cfg.number({
      label: "Starting Wallet",
      description: "Coins a new player starts with.",
      default: 100,
      min: 0,
      group: "Currency",
    }),
    startingBank: cfg.number({
      label: "Starting Bank",
      description: "Banked coins a new player starts with.",
      default: 0,
      min: 0,
      group: "Currency",
    }),
    maxBalance: cfg.number({
      label: "Maximum Balance",
      description: "Winnings past this total are forfeited.",
      default: 1000000,
      min: 1000,
      group: "Currency",
    }),
    blackjackMinBet: cfg.number({
      label: "Blackjack Minimum Bet",
      description: "Smallest allowed blackjack bet.",
      default: 5,
      min: 1,
      group: "Blackjack",
    }),
    blackjackMaxBet: cfg.number({
      label: "Blackjack Maximum Bet",
      description: "Largest allowed blackjack bet.",
      default: 500,
      min: 1,
      group: "Blackjack",
    }),
    blackjackPayout: cfg.number({
      label: "Blackjack Payout",
      description: "Profit multiplier paid on a natural blackjack.",
      default: 1.5,
      min: 1,
      max: 5,
      step: 0.5,
      group: "Blackjack",
    }),
    rouletteMinBet: cfg.number({
      label: "Roulette Minimum Bet",
      description: "Smallest allowed roulette bet.",
      default: 5,
      min: 1,
      group: "Roulette",
    }),
    rouletteMaxBet: cfg.number({
      label: "Roulette Maximum Bet",
      description: "Largest allowed roulette bet.",
      default: 500,
      min: 1,
      group: "Roulette",
    }),
    crimeCooldown: cfg.duration({
      label: "Crime Cooldown",
      description: "How long a member waits between crimes.",
      default: "10m",
      quickPicks: ["1m", "5m", "10m", "30m", "1h"],
      group: "Crime",
    }),
    workCooldown: cfg.duration({
      label: "Work Cooldown",
      description: "How long a member waits between shifts.",
      default: "30m",
      quickPicks: ["5m", "30m", "1h", "24h"],
      group: "Grinds",
    }),
    begCooldown: cfg.duration({
      label: "Beg Cooldown",
      description: "How long a member waits between begging.",
      default: "2m",
      quickPicks: ["1m", "2m", "5m", "15m"],
      group: "Grinds",
    }),
    fishCooldown: cfg.duration({
      label: "Fish Cooldown",
      description: "How long a member waits between fishing trips.",
      default: "10m",
      quickPicks: ["1m", "10m", "30m", "1h"],
      group: "Grinds",
    }),
    mineCooldown: cfg.duration({
      label: "Mine Cooldown",
      description: "How long a member waits between mining shifts.",
      default: "10m",
      quickPicks: ["1m", "10m", "30m", "1h"],
      group: "Grinds",
    }),
    useRewardMin: cfg.number({
      label: "Consumable Minimum Reward",
      description: "Smallest payout from using a consumable shop item.",
      default: 20,
      min: 0,
      group: "Shop",
    }),
    useRewardMax: cfg.number({
      label: "Consumable Maximum Reward",
      description: "Largest payout from using a consumable shop item.",
      default: 120,
      min: 0,
      group: "Shop",
    }),
    shopItems: cfg.stringList({
      label: "Shop Items",
      description:
        "One item per line as name | price | description | roleId | consumable | stock. roleId, consumable (yes/no), and stock are optional; empty stock means unlimited.",
      default: [],
      group: "Shop",
    }),
  }),
});
