name: Addons CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: CI / typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Dependencies
        run: nix-shell --run "bun install --frozen-lockfile"

      - name: Run Typecheck
        run: nix-shell --run "bun run typecheck"

  lint:
    name: CI / lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Dependencies
        run: nix-shell --run "bun install --frozen-lockfile"

      - name: Run Linter
        run: nix-shell --run "bun run lint"
